

server:
  port: 8070

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ms_pg_sql:5432/order
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: ms-kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.add.type.headers: false
        spring.json.type.mapping: orderConfirmation:com.ecom.orderservice.kafka.dto.OrderConfirmationDto
application:
  config:
    customer-url: http://customer-service:8222/api/v1/customers
    product-url: http://product-service:8222/api/v1/products
    payment-url: http://payment-service:8222/api/v1/payments

eureka:
  instance:
    hostname: order-service
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/