spring:
  application:
    name: notification-service

  config:
    import: optional:configserver:http://localhost:8888

  mongodb:
    uri: mongodb://Surya:Surya@localhost:27017/notification?authSource=admin