spring:
  application:
    name: notification-service

  config:
    import: optional:configserver:http://config-service:8888

  mongodb:
    uri: mongodb://Surya:Surya@ms_mongo_db:27017/notification?authSource=admin